version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: root
      POSTGRES_DB: one_to_many
    ports:
      - 5433:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
